// Generated by CoffeeScript 1.9.0
var HyperQuery, VNode, select, _;

select = require('vtree-select');

VNode = require('virtual-dom/vnode/vnode');

_ = require('underscore');

HyperQuery = (function() {
  HyperQuery.prototype.selector = '';

  HyperQuery.prototype.nodes = null;

  function HyperQuery(_at_nodes, _at_selector) {
    this.nodes = _at_nodes != null ? _at_nodes : [];
    this.selector = _at_selector != null ? _at_selector : '';
    if (!_.isArray(this.nodes)) {
      this.nodes = [this.nodes];
    }
  }

  HyperQuery.prototype.find = function(selector) {
    return new HyperQuery(select(selector)(this.node), selector);
  };

  return HyperQuery;

})();

module.exports = {
  $: function(something, root) {
    if (something == null) {
      return new HyperQuery;
    } else if (_.isString(something && (root != null) && root instanceof VNode)) {
      return new HyperQuery(select(something)(root), selector);
    } else if (something instanceof VNode) {
      return new HyperQuery('', s);
    }
    return new HyperQuery;
  }
};

//# sourceMappingURL=hyper-query.js.map
